---
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - skip-changelog

  categories:
    - title: Breaking Changes 🛠
      labels:
        - backwards-incompatible

    - title: New Features 🎉
      labels:
        - enhancement

    - title: Other Changes
      labels:
        - "*"
