---
name: QA🚦

on:
  pull_request: {}
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main

jobs:
  build_test_container:
    name: 'Build test container'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          publish: 'false'

  test_gem_installation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

  tests:
    needs:
      - build_test_container
      - test_gem_installation
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
